# Generated by Django 2.1.7 on 2019-03-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
