# Generated by Django 2.1.3 on 2019-02-13 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Drug class',
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('drug_class', models.ManyToManyField(related_name='Drug_class', to='pharmadoc.DrugClass')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50)),
                ('amount_containers', models.PositiveIntegerField(default=1, verbose_name='Amount of ordered Containers')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of one container', max_digits=10)),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('l', 'l'), ('mg', 'mg'), ('g', 'g')], max_length=10)),
                ('delivery_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=250)),
                ('consumed', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50)),
                ('dose', models.CharField(max_length=250, verbose_name='concentration active substance')),
                ('type', models.CharField(choices=[('veterinary', 'veterinary'), ('human', 'human')], max_length=50)),
                ('animal_species', models.CharField(max_length=250, null=True)),
                ('umwidmungsstufe', models.PositiveIntegerField()),
                ('storage_instructions', models.CharField(blank=True, max_length=400, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/pharmacy/%Y/%m/%d/')),
                ('alarm_value', models.PositiveIntegerField(blank=True, help_text='Please enter a number of full containers. If less container are available Alessia gets a mail.', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmadoc.Company')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmadoc.Molecule')),
            ],
            options={
                'verbose_name': 'Product Info',
                'verbose_name_plural': 'Product Infos',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('amount_containers', models.PositiveIntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('procedure_control', models.CharField(blank=True, max_length=800, null=True)),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='uploads/order/%Y/%m/%d/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='uploads/order/%Y/%m/%d/')),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Order')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Person')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Pharmacy'),
        ),
    ]
