# Generated by Django 2.1 on 2018-09-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50)),
                ('molecule', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('veterinary', 'veterinary'), ('human', 'human')], max_length=50)),
                ('amount_containers', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of one container')),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('g', 'g')], max_length=10)),
                ('delivery_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=250)),
                ('consumed', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('amount_containers', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of one container')),
                ('comment', models.CharField(blank=True, max_length=1500, null=True)),
                ('procedure_control', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
