# Generated by Django 2.1.2 on 2018-10-24 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('trading_name', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50)),
                ('active_substance', models.CharField(max_length=250)),
                ('dose', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(choices=[('veterinary', 'veterinary'), ('human', 'human')], max_length=50)),
                ('animal_species', models.CharField(max_length=250, null=True)),
                ('umwidmungsstufe', models.PositiveIntegerField()),
                ('storage_instructions', models.CharField(max_length=400, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(null=True, upload_to='uploads/pharmacy/%Y/%m/%d/')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Company')),
                ('drug_class', models.ManyToManyField(related_name='Drug_class', to='pharmadoc.DrugClass')),
            ],
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50)),
                ('molecule', models.CharField(max_length=250)),
                ('amount_containers', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of one container', max_digits=10)),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('l', 'l'), ('mg', 'mg'), ('g', 'g')], max_length=10)),
                ('delivery_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=250)),
                ('consumed', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('alarm_value', models.PositiveIntegerField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('amount_containers', models.PositiveIntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('procedure_control', models.CharField(blank=True, max_length=800, null=True)),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='uploads/stockproduct/%Y/%m/%d/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='uploads/stockproduct/%Y/%m/%d/')),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Person')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.StockProduct')),
            ],
        ),
    ]
