# Generated by Django 2.1.2 on 2018-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmadoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
