# Generated by Django 2.1 on 2018-09-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmadoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Person'),
        ),
    ]
