# Generated by Django 2.1 on 2018-09-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmadoc', '0002_submission_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Company'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='drug_class',
            field=models.ManyToManyField(null=True, related_name='Drug_class', to='pharmadoc.DrugClass'),
        ),
    ]
