# Generated by Django 2.1.2 on 2018-10-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmadoc', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50),
        ),
    ]
