# Generated by Django 2.1 on 2018-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmadoc', '0003_auto_20180926_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='drug_class',
            field=models.ManyToManyField(related_name='Drug_class', to='pharmadoc.DrugClass'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
