# Generated by Django 2.1.2 on 2018-10-17 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmadoc', '0003_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
