# Generated by Django 2.1 on 2018-09-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmadoc', '0004_auto_20180926_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmadoc.Pharmacy'),
        ),
    ]
