# Generated by Django 2.1.2 on 2018-10-18 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmadoc', '0004_auto_20181017_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
